### ISSUE TITLE
FontAwesome v 4.7

### ISSUE THREAD

**Issue by hSloan** [spl/font-awesome-type#2]
Thanks alot for this package! I was wondering, will you be updating this package with Font Awesome(v 4.7)? 41 new icons have been added

**Comment by spl** [comment]
@hSloan Thanks for your interest. I had planned on doing the update, but life intervened. If you wish to have a go, I would appreciate it. Otherwise, I'll try when I can find the time.

**Comment by hSloan** [comment]
@spl Ah, I totally understand. I would love to give it a go as soon as I can. Thanks for the opportunity to contribute.

**Comment by hSloan** [comment]
I see all the 4.7 icons have been added already. Thanks!
